[project]
name = "ubel"
version = "0.3.1"
description = "Supply-chain dependency firewall for: Python, Node, PHP, Ubuntu, Debian, Red Hat, and Almalinux."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "python-dotenv",
    "cvss",
    "reportlab",
    "distro",
    "packaging"
]

[project.scripts]
ubel-pip = "ubel.cli:pip_mode"
ubel-npm = "ubel.cli:npm_mode"
ubel = "ubel.cli:linux_mode"
